import React, { createContext, useState, useContext } from 'react';

const LanguageContext = createContext();

export const translations = {
  en: {
    appName: "Khedma App",
    loginTitle: "Service Application",
    username: "Username",
    password: "Password",
    login: "Login",
    welcome: "Welcome",
    role: "Role",
    notifications: "Notifications",
    takeAttendance: "Take Attendance",
    birthdays: "Birthdays",
    classDisplay: "Class Display",
    editVisitation: "Edit Visitation",
    addStudents: "Add Students",
    addStaff: "Add Staff",
    activateDeactivate: "Activate / Deactivate",
    editStaff: "Edit Staff Details",
    editStudents: "Edit Student Details",
    logs: "System Logs",
    reset: "Reset Attendance",
    whatsappTest: "WhatsApp Test",
    backupData: "Database Backup",
    importData: "Import Data",
    loading: "Loading...",
    error: "Error",
    comingSoon: "Coming Soon",
    development: "This feature is under development",
    roleAdmin: "Administrator",
    rolePrincipal: "Principal",
    roleCoPrincipal: "Stage Servant",
    roleTeacher: "Teacher",
    selectTeacher: "Select Teacher",
    assignStudents: "Assign Students",
    staffList: "Staff List",
    attendanceSheet: "Attendance Sheet",
    selectClass: "Select Class",
    viewAttendanceSheet: "View Attendance Sheet",
    gradeLevel: "Grade Level",
    motherPhone: "Mother's Phone",
    fatherPhone: "Father's Phone",
    birthdate: "Birthdate",
    lastAttendance: "Last Attendance",
    never: "Never",
    attendanceDate: "Attendance Date",
    allPresent: "All Present",
    allAbsent: "All Absent",
    registerAttendance: "Register Attendance",
    totalAttendance: "Total Attendance",
    success: "Success",
    attendanceRegistered: "Attendance registered successfully!",
    selectClassFirst: "Please select a class first",
    studentName: "Student Name",
    saveChanges: "Save Changes",
    editStudentTitle: "Edit Student Details",
    editStaffTitle: "Edit Staff Details",
    active: "Active",
    inactive: "Inactive",
    status: "Status",
    save: "Save",
    cancel: "Cancel",
    confirm: "Confirm",
    ok: "OK",
    gender: "Gender",
    search: "Search...",
    noStudents: "No students found in this class.",
    lastAbsentDate: "Last Absent Date",
    servant: "Servant",
    principalServant: "Principal Servant",
    stageServant: "Stage Servant",
    fullNameLabel: "Full Name",
    roleLabel: "Role",
    chooseRole: "-- Choose Role --",
    phoneLabel: "Phone Number",
    telegramChatIdLabel: "Telegram Chat ID",
    telegramChatIdPlaceholder: "e.g. 123456789",
    telegramChatIdHint: "Send /start to Telegram Bot to get your Chat ID",
    selectLevel: "-- Select Level --",
    selectClass: "-- Select Class --",
    chooseRoleFirstPrompt: "Please choose a role first to configure level and class",
    chooseLevelFirstPrompt: "Please choose a level first to configure class",
    principalNoLevelPrompt: "Principal role does not require level or class assignment",
    usernameLabel: "Username",
    passwordLabel: "Password",
    addToQueue: "Add to Queue",
    submitAll: "Submit All",
    credentialsTitle: "Access Credentials",
    copyClipboard: "Copy to Clipboard",
    close: "Close",
    level1: "1st Level",
    level2: "2nd Level",
    level3: "3rd Level",
    phonePlaceholder: "e.g. 01000000000",
    pickBirthdate: "Pick birthdate",
    filterAll: "All",
    filterLogins: "Log in",
    filterAttendance: "Attendance",
    filterUsers: "User Mgmt",
    filterOthers: "Others",
    performedByLabel: "Performed by: ",
    targetLabel: "Target: ",
    classLabel: "Class: ",
    noLogsFound: "No logs found matching this filter.",
    timeAll: "All Time",
    timeWeek: "Last Week",
    time2Weeks: "Last 2 Weeks",
    timeMonth: "Last Month",
    timeYear: "Last Year",
    timeCustom: "Custom Period",
    tayo: "Taio",
    manageTayo: "Manage Taio",
    giveTayo: "Give Taio",
    displayDeductTayo: "Display & Deduct Taio",
    searchStudent: "Search by student name...",
    sortBy: "Sort By:",
    alphabetical: "Name",
    balance: "Balance",
    level: "Level:",
    classFilter: "Class:",
    levelPrefix: "Year ",
    amountToGive: "Amount",
    reasonPlaceholder: "Reason / Note",
    giveBtn: "Give",
    deductTayo: "Deduct Taio",
    logsTab: "Logs",
    noLogs: "No logs found",
    amountToDeduct: "Amount to deduct",
    confirmDeduct: "Confirm Deduction",
    invalidNumber: "Invalid number",
    reasonRequired: "Reason is required",
    tayoAddedSuccess: "Taio added successfully",
    tayoAddError: "Error occurred while adding Taio",
    tayoDeductSuccess: "Taio deducted successfully",
    tayoDeductError: "Error occurred while deducting Taio",
    cancelBtn: "Cancel",
    closeModal: "Close",
  },
  ar: {
    appName: "تطبيق الخدمة",
    loginTitle: "تطبيق الخدمة",
    username: "اسم المستخدم",
    password: "كلمة المرور",
    login: "تسجيل الدخول",
    welcome: "مرحباً بك",
    role: "الرتبة",
    notifications: "الاشعارات",
    takeAttendance: "تسجيل حضور",
    birthdays: "اعياد الميلاد",
    classDisplay: "عرض الفصل",
    editVisitation: "تعديل خدام الافتقاد",
    addStudents: "اضافه المخدومين",
    addStaff: "اضافه خدام",
    activateDeactivate: "تفعيل / تعطيل",
    editStaff: "تعديل بينات الخدام",
    editStudents: "تعديل بينات المخدومين",
    logs: "سجلات النظام",
    reset: "إعادة ضبط العدادات",
    whatsappTest: "تجربة التليجرام",
    backupData: "النسخ الاحتياطي",
    importData: "استيراد البيانات",
    loading: "جاري التحميل...",
    error: "خطأ",
    comingSoon: "قريباً",
    development: "هذه الميزة قيد التطوير",
    roleAdmin: "أدمن",
    rolePrincipal: "أمين الخدمة",
    roleCoPrincipal: "أمين مرحلة",
    roleTeacher: "خادم فصل",
    selectTeacher: "اختار الخادم",
    assignStudents: "توزيع المخدومين",
    staffList: "عرض بينات الخدام",
    attendanceSheet: "دفتر الغياب",
    selectClass: "اختار الفصل",
    viewAttendanceSheet: "عرض كشف الحضور",
    gradeLevel: "السنة الدراسية",
    motherPhone: "تليفون الأم",
    fatherPhone: "تليفون الأب",
    birthdate: "تاريخ الميلاد",
    lastAttendance: "آخر تاريخ حضور",
    never: "لم يحضر بعد",
    attendanceDate: "تاريخ تسجيل الحضور",
    allPresent: "الكل حاضر",
    allAbsent: "الكل غائب",
    registerAttendance: "تسجيل الحضور",
    totalAttendance: "إجمالي الحضور",
    success: "نجاح",
    attendanceRegistered: "تم تسجيل الحضور بنجاح!",
    selectClassFirst: "يرجى اختيار فصل أولاً",
    studentName: "اسم المخدوم",
    saveChanges: "حفظ التعديلات",
    editStudentTitle: "تعديل بيانات المخدوم",
    editStaffTitle: "تعديل بيانات الخادم",
    active: "مفعل",
    inactive: "معطل",
    status: "الحالة",
    save: "حفظ",
    cancel: "إلغاء",
    confirm: "تأكيد",
    ok: "حسناً",
    gender: "النوع",
    search: "بحث...",
    noStudents: "لا يوجد مخدومين في هذا الفصل.",
    lastAbsentDate: "تاريخ آخر غياب",
    servant: "خادم",
    principalServant: "أمين الخدمة",
    stageServant: "أمين مرحلة",
    fullNameLabel: "الاسم رباعي",
    roleLabel: "المنصب",
    chooseRole: "-- اختر المنصب --",
    phoneLabel: "رقم التليفون",
    telegramChatIdLabel: "معرف التليجرام (Telegram Chat ID)",
    telegramChatIdPlaceholder: "مثال: 123456789",
    telegramChatIdHint: "للحصول عليه أرسل /start لبوت التليجرام",
    selectLevel: "-- اختر المرحلة --",
    selectClass: "-- اختر الفصل --",
    chooseRoleFirstPrompt: "برجاء اختيار المنصب أولاً لتحديد المرحلة والفصل",
    chooseLevelFirstPrompt: "برجاء اختيار المرحلة أولاً لتحديد الفصل",
    principalNoLevelPrompt: "أمين الخدمة لا يتطلب تحديد مرحلة أو فصل",
    usernameLabel: "اسم المستخدم",
    passwordLabel: "كلمة المرور",
    addToQueue: "إضافة إلى القائمة",
    submitAll: "إرسال الكل",
    credentialsTitle: "بيانات الدخول",
    copyClipboard: "نسخ إلى الحافظة",
    close: "إغلاق",
    level1: "سنة أولى",
    level2: "سنة ثانية",
    level3: "سنة ثالثة",
    phonePlaceholder: "مثال: 01000000000",
    pickBirthdate: "اختر تاريخ الميلاد",
    filterAll: "الكل",
    filterLogins: "عمليات الدخول",
    filterAttendance: "حضور وغياب",
    filterUsers: "إدارة الحسابات",
    filterOthers: "أخرى",
    performedByLabel: "قام به: ",
    targetLabel: "المستهدف: ",
    classLabel: "الفصل: ",
    noLogsFound: "لا توجد سجلات مطابقة لهذا الفلتر.",
    timeAll: "كل الأوقات",
    timeWeek: "آخر أسبوع",
    time2Weeks: "آخر أسبوعين",
    timeMonth: "آخر شهر",
    timeYear: "آخر سنة",
    timeCustom: "فترة مخصصة",
    tayo: "طايو",
    manageTayo: "إدارة طايو",
    giveTayo: "إعطاء طايو",
    displayDeductTayo: "عرض و خصم طايو",
    searchStudent: "ابحث باسم المخدوم...",
    sortBy: "ترتيب:",
    alphabetical: "الأبجدية",
    balance: "الرصيد",
    level: "المرحلة:",
    classFilter: "الفصل:",
    levelPrefix: "سنة ",
    amountToGive: "الكمية",
    reasonPlaceholder: "السبب / ملاحظة",
    giveBtn: "إعطاء",
    deductTayo: "خصم طايو",
    logsTab: "السجل",
    noLogs: "لا توجد سجلات",
    amountToDeduct: "الكمية المراد خصمها",
    confirmDeduct: "تأكيد الخصم",
    invalidNumber: "الرقم غير صحيح",
    reasonRequired: "السبب مطلوب",
    tayoAddedSuccess: "تم إضافة طايو بنجاح",
    tayoAddError: "حدث خطأ أثناء الإضافة",
    tayoDeductSuccess: "تم خصم طايو بنجاح",
    tayoDeductError: "حدث خطأ أثناء الخصم",
    cancelBtn: "إلغاء",
    closeModal: "إغلاق",
    classSeraphim: "فصل السيرافيم",
    classCherubim: "فصل الشاروبيم",
    classRaphael: "الملاك رفائيل",
    classMichael: "الملاك ميخائيل",
    classSuriel: "الملاك سوريال",
    classGabriel: "الملاك غبريال",
    editStaffSuccess: "تم حفظ التعديل بنجاح.",
    editStaffFailure: "فشل حفظ التعديل",
    deleteStaffSuccess: "تم حذف الحساب بنجاح.",
    deleteStaffFailure: "فشل حذف الحساب",
    deleteStaffConfirm: "هل أنت متأكد من رغبتك في حذف هذا الخادم؟ لا يمكن التراجع عن هذا الإجراء.",
    confirmDeleteTitle: "تأكيد الحذف",
    deleteLabel: "حذف",
    cancelLabel: "إلغاء",
  }
};

export const LanguageProvider = ({ children }) => {
  const [locale, setLocale] = useState('ar');

  const t = (key) => {
    return translations[locale][key] || key;
  };

  const toggleLanguage = () => {
    setLocale((prev) => (prev === 'ar' ? 'en' : 'ar'));
  };

  return (
    <LanguageContext.Provider value={{ locale, setLocale, t, toggleLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
